# Use the official Node.js image as a base
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the backend package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the backend code and frontend files
COPY . .
COPY ../frontend ./public

# Expose the application port
EXPOSE 3000

# Run the application
CMD ["npm", "run", "start:prod"]
